<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeFile="Admin.aspx.cs" Inherits="AWP__project_.WebForm4" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class ="container-fluid">
        <asp:Label ID="Welcome" CssClass="d-flex justify-content-center text-primary" Font-size="XX-Large" Font-Bold="true" runat="server" ></asp:Label>
    <div class ="row justify-content-start mt-5">
        <div class="col-sm-1">
            <asp:Label ID="title"  runat="server" Text="Id"  Font-Size="X-Large" ForeColor="White"></asp:Label>
        </div>
        <div class="col-md-3" >
            <asp:TextBox ID="titletext" CssClass="border-danger" TextMode="Number" runat="server" AutoPostBack="True" OnTextChanged="titletext_TextChanged"></asp:TextBox>
        </div>
        <div class="col-sm-1">
            <asp:Label ID="author" runat="server" Text="Author" Font-Size="X-Large" ForeColor="White"></asp:Label>
        </div>
        <div class="col-md-3">
            <asp:TextBox ID="authortext" CssClass="border-danger" runat="server" AutoPostBack="True" OnTextChanged="authortext_TextChanged"></asp:TextBox>
        </div>
    </div>
    <br />
    <div class="row justify-content-start">
        <div class="col-sm-1">
        <div class="btn-group" role="group" aria-label="Basic example">
            <asp:Button ID="search" CssClass="btn btn-outline-primary mx-1 btn-sm" runat="server" Text="Search" OnClick="search_Click" />
            <asp:Button ID="allposts" CssClass="btn btn-outline-primary mx-1 btn-sm" runat="server" Text="AllPost" OnClick="allposts_Click" />
            <asp:Button ID="byauthor" CssClass="btn btn-outline-primary mx-1 btn-sm" runat="server" Text="ByAuthor" OnClick="byauthor_Click" />
            <asp:Button ID="newpost" CssClass="btn btn-outline-primary mx-1 btn-sm" runat="server" Text="NewPost" PostBackUrl="~/NewPost.aspx"  />
            <asp:Button ID="logout"  CssClass="btn btn-outline-primary mx-1 btn-sm" runat="server" Text="LogOut" OnClick="logout_Click" />
        </div>
        </div>
    </div>
</div>
    <div class="d-flex justify-content-start mb-0 mt-4" style="overflow-x: auto; max-width: 100%;">
       <asp:GridView ID="Data" runat="server" DataSourceID="datasource" CssClass="responsive-grid container-fluid mt-3 m-2" AutoGenerateColumns="False" DataKeyNames="PostId" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AllowPaging="True" BorderStyle="Dashed" CellPadding="4" ForeColor="#333333">
           <AlternatingRowStyle BackColor="White" />
           <Columns>
               <asp:BoundField DataField="PostId" HeaderText="PostId" InsertVisible="False" ReadOnly="True" SortExpression="PostId" />
               <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
               <asp:BoundField DataField="Content" HeaderText="Content" SortExpression="Content" />
               <asp:BoundField DataField="PostDate" HeaderText="PostDate" SortExpression="PostDate" />
               <asp:BoundField DataField="AuthorName" HeaderText="AuthorName" SortExpression="AuthorName" />
               <asp:BoundField DataField="Image" HeaderText="Image" SortExpression="Image" />
               <asp:BoundField DataField="AuthorDescription" HeaderText="AuthorDescription" SortExpression="AuthorDescription" />
               <asp:BoundField DataField="AuthorImage" HeaderText="AuthorImage" SortExpression="AuthorImage" />
               <asp:BoundField DataField="Category" HeaderText="Category" SortExpression="Category" />
           </Columns>
           <EditRowStyle BackColor="#2461BF" />
           <EmptyDataRowStyle BorderStyle="Solid" />
           <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
           <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
           <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
           <RowStyle BackColor="#EFF3FB" />
           <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
           <SortedAscendingCellStyle BackColor="#F5F7FB" />
           <SortedAscendingHeaderStyle BackColor="#6D95E1" />
           <SortedDescendingCellStyle BackColor="#E9EBEF" />
           <SortedDescendingHeaderStyle BackColor="#4870BE" />

        </asp:GridView>

        <asp:SqlDataSource ID="datasource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [post]" UpdateCommand="UPDATE [post] SET [Title] = @Title, [Content] = @Content, [AuthorName] = @AuthorName, [Image] = @Image, [AuthorDescription] = @AuthorDescription, [AuthorImage] = @AuthorImage, [Category] = @Category WHERE [PostId] = @PostId" DeleteCommand="DELETE FROM [post] WHERE [PostId] = @PostId"></asp:SqlDataSource>

    </div>
</asp:Content>
